version: '3'

services:
  registry:
    image: registry:2
    container_name: registry_service
    restart: always
    network_mode: bridge
    ports:
    - "${PORT}:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/data
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /mnt/auth/htpasswd
      REGISTRY_HTTP_TLS_CERTIFICATE: /mnt/cert/domain.cer
      REGISTRY_HTTP_TLS_KEY: /mnt/cert/domain.key
    volumes:
      - ./data:/mnt/data
      - ./auth:/mnt/auth
      - $HOME/Work/nginx/cert:/mnt/cert
