global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  static_configs:
  - targets: ['prometheus:9090']
  # - targets: ['192.168.1.1:3023']

- job_name: go-web_dev
  metrics_path: /prometheus
  static_configs:
  - targets: ['192.168.1.1:3023']
