version: '3'

services:
  mongo:
    image: mongo:5
    container_name: mongo_db
    # restart: always

    environment:
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=root
  
    networks: ["mongo"]
    ports: ["127.0.0.1:27017:27017"]

    volumes:
    - $HOME/Work/docker/mongodb/data:/data/db

networks:
  mongo: {name: "mongo", driver: "bridge"}
