version: '3'

# volumes:
#  nextcloud:
#  db:

services:
  db:
    image: mariadb:10.5
    container_name: nextcloud_db_service
    restart: always
    network_mode: bridge
    volumes: ["./db:/var/lib/mysql"]

    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud

    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  app:
    image: nextcloud:22-apache
    container_name: nextcloud_app_service
    restart: always
    network_mode: bridge
    ports: ["${PORT}:80"]
    links: ["db"]
    volumes: ["./data:/var/www/html"]
    environment:
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_HOST=db
