version: '3'

# volumes:
#  nextcloud:
#  db:

services:
  db:
    image: mariadb:10.5
    container_name: nextcloud_mysql
    restart: always

    # network_mode: bridge
    networks: ["nextcloud"]
    volumes: ["./db:/var/lib/mysql"]

    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud

    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

  app:
    image: nextcloud:22-apache
    container_name: nextcloud_app
    restart: always
    depends_on: ["db"]

    # links: ["db"]
    # network_mode: bridge
    networks: ["nextcloud"]
    ports: ["127.0.0.1:${PORT}:80"]

    volumes: ["./data:/var/www/html"]

    environment:
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_HOST=db

networks:
  nextcloud: {name: "nextcloud", driver: "bridge"}
