version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    networks: ["mysql"]
    # network_mode: bridge
    ports: ["127.0.0.1:${PORT}:3306"]

    volumes:
    # - $HOME/Work/docker/mysql/data:/var/lib/mysql/
    - ./data/mysql:/var/lib/mysql/
    - ./data/mysql.cnf:/etc/mysql/my.cnf
    environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

networks:
  mysql: {name: "mysql", driver: "bridge", external: false}
