version: '3'

services:
  mysql:
    image: mysql:8-debian
    container_name: mysql_db
    restart: always

    networks: ["mysql"]
    # network_mode: bridge
    ports: ["127.0.0.1:${PORT}:3306"]

    volumes:
    - ./data/mysql:/var/lib/mysql/
    # - ./data/mysql.cnf:/etc/mysql/my.cnf

    environment:
    - TZ=Asia/Shanghai
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

    # make sure character_set_client, character_set_connection, character_set_results is utf8mb4 rather than latin1
    command:
    - "--character-set-server=utf8mb4"
    - "--collation-server=utf8mb4_general_ci"
    - "--skip-character-set-client-handshake"

networks:
  mysql: {name: "mysql", driver: "bridge", external: false}
