version: '3'

services:
  mysql:
    image: mysql:8
    container_name: mysql_service
    restart: always
    network_mode: bridge
    volumes:
      - $HOME/Work/docker/mysql/my.cnf:/etc/mysql/my.cnf
      - $HOME/Work/docker/mysql/data:/var/lib/mysql/
      - $HOME/Work/docker/mysql:/mnt/work
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
