version: '3'

services:
  redis:
    image: redis:7-alpine
    # restart: always
    ports:
    - '6379:6379'
    environment:
    # ALLOW_EMPTY_PASSWORD is recommended only for development.
    - ALLOW_EMPTY_PASSWORD=yes
    - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes: 
    # - redis_storage:/data
    - ./configs:/etc/redis
    - ./data:/data
    # command: redis-server /etc/redis/redis.conf --save 30 10 --loglevel warning --requirepass d2jvkpn
    command: redis-server /etc/redis/redis.conf --save 30 10 --loglevel warning

#volumes:
#  redis_storage:
#    name: redis_storage
#    driver: local
